# Generated by Django 3.2.7 on 2021-09-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da consulta')),
                ('motivo_consulta', models.CharField(max_length=250, verbose_name='Motivo da consulta')),
                ('peso_atual', models.FloatField(verbose_name='Peso atual')),
                ('medicamento_atual', models.TextField(blank=True)),
                ('medicamentos_prescritos', models.TextField(blank=True)),
                ('exames_prescritos', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pet')),
            ],
        ),
    ]
